apiVersion: apps/v1
kind: Deployment
metadata:
  name: component1-deployment
  labels:
    app: component1
spec:
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      app: component1
  template:
    metadata:
      labels:
        app: component1
    spec:
      containers:
      - name: component1-container
        image: "{{ .Values.image }}"
        env:
        - name: MQTT_SERVER
          value: "{{ .Values.env.MqttServer }}"
        - name: MQTT_PORT
          value: "{{ .Values.env.MqttPort }}"
        command:
          - sleep
          - "99999"
