kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30950
    hostPort: 3000
    listenAddress: "127.0.0.1"
    protocol: TCP
  - containerPort: 30951
    hostPort: 23
    listenAddress: "127.0.0.1"
    protocol: TCP
  - containerPort: 32570
    hostPort: 5137
    listenAddress: "127.0.0.1"
    protocol: TCP