apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: app1-cluster-config-values
    files:
      - values.yaml=app1-cluster-config-values.yaml

# configurations:
#   - kustomizeconfig.yaml
